strings="hii aryan yadav how was your day"

# if you have to calculate occurence of a given letter/word/char in a given string...
print(strings.count("aryan"))

#if we have to capitilize first letter in a given string.....
print(strings.capitalize())

#if we have to calculate given char/word in a given string...
print(strings.find("yan")) 

#if we have to convert given string into capital letter....
print(strings.upper())

#if we have to convert given string into small letter...
print(strings.lower()) 

#if we have to replace any char/word in a given string...
print(strings.replace("aryan","yadav"))