import datetime
today=datetime.date.today()
print(today.day,today.month,today.year)
d=datetime.date(2020,2,20)
print(d)
print('weekday =',d.weekday())
print()
print(d.strftime("%d-%m-%y"))
print(d.strftime("%d-%b-%Y"))
print(d.strftime("%d-%b-%Y"))
print(d.strftime("%d-%B-%Y"))
print(d.strftime("%d-%b-%Y, %a"))
print(d.strftime("%d-%b-%Y, %A"))
print(d.strftime("%d-%b-%Y"))
print(d.strftime("%d-%b-%Y"))
print()
now=datetime.datetime.now()
print(now)
print(now.day,now.month,now.year,now.hour,now.minute,now.second,now.microsecond)
prev=datetime.datetime(2020,4,18)
print(prev>now)
dt1=datetime.datetime(2020,2,2,9)
dt2=datetime.datetime(2020,2,20,17,30)
print(dt1,dt2,dt2-dt1)
d1=datetime.date(2020,3,15)
d2=datetime.date(2020,3,8)
print(d1,d2,d2-d1)
diff=datetime.timedelta(weeks=1)
print(diff+d1)
print(diff.days,diff.seconds,diff.microseconds)
print(diff.total_seconds())
d=datetime.date(2019,8,21)
diff=datetime.timedelta(days=200)
print(diff+d)
dt=datetime.datetime(2020,2,2,9,30,45)
diff2=datetime.timedelta(seconds=86399)
print(diff2+dt)
print(diff+diff2)
print(diff2+d)
with open('/Users/shauryaks/Downloads/Octave Files/cost',mode='r') as cost_file:
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
    print(cost_file.readline())
cost_file=open('/Users/shauryaks/Downloads/Octave Files/cost',mode='r')
print(cost_file.read())
print(__name__)
print(abs(-2))


